### ISSUE TITLE
StringTable

### ISSUE THREAD

**Issue by aidar666** [gonutz/wui#8] opened 2021-07-28 08:45 UTC
I used
`var AStringTable = wui.NewStringTable("NO", "ANALYZER NAME", "DRIVER")`
to create StringTable, and got this:
![unnamed](https://user-images.githubusercontent.com/53258280/127292721-fc1c19a7-c16a-45cf-9f95-f43c852ecf5c.png)

How do I create a StringTable properly? Why do I get 4 columns instead of 3 and how do I set full names to columns? Also i dunno how to add rows to this, will be glad to get any help

**Comment by gonutz** [comment] 2021-07-28 11:05
Disclaimer: the StringTable is something that was born out of necessity to show a table in one way or another. I am not very happy with it but have no time to create a better thing as a replacement.

You are correctly creating the table, right now you can only have a fixed number of columns, i.e. the number of strings you put in the constructor, 3 in your case. The column widths will be adjusted to fit the texts usually, you might have encountered a bug. When I get around to it, I will investigate why you seem to have a double-high header row with missing characters.

To insert a string, use [SetCell](https://pkg.go.dev/github.com/gonutz/wui/v2#StringTable.SetCell) and it will grow the table as needed.

The reason why you see extra rows and columns is because that is what the default Windows API table does. This is a very thin wrapper around the Windows API.

PS: Are you coming from Delphi? I recognize the 'A' at the start of your variable :-)

**Comment by aidar666** [comment] 2021-07-28 11:38
So i tried to do this:
`...`
`var AStringTable = wui.NewStringTable("No", "AnalyzerName", "Driver")`
`...`
`AStringTable.SetCell(0, 0, "101")`
`AStringTable.SetCell(1, 0, "analyzer1")`
`AStringTable.SetCell(2, 0, "driver1")`
`AStringTable.SetCell(0, 1, "102")`
`AStringTable.SetCell(1, 1, "analyzer2")`
`AStringTable.SetCell(2, 1, "driver2")`
`...`
and got this:
![изображение](https://user-images.githubusercontent.com/53258280/127315748-1158bfef-6d9b-4ad9-9d46-7dd978324e35.png)

I`m running it on Windows 10 x64, is that a problem?

P.S: no I am not, the "A" means "Analyzers". There is supposed to be a several tables with my data from SQL, so I decided to name them this way

**Comment by gonutz** [comment] 2021-07-28 12:02
I am looking into this, but right now I have not much time and after ten minutes the problem is not immediately obvious. I will get back to you soon on this :-)

**Comment by aidar666** [comment] 2021-07-28 15:17
I found that at str 66 in string_table.go there is used syscall.UTF16PtrFromString function, that eats string variable and gives back us *uint16 variable.
It looks like this:
![изображение](https://user-images.githubusercontent.com/53258280/127345570-07013dfa-f931-409a-b524-dd7d6773f379.png)
I am not sure, but i think its a reason we get one symbol instead of whole string.

**Comment by gonutz** [comment] 2021-07-28 20:07
That is actually fine, I have checked that this pointer really is the UTF-16 encoded string that I told it to be. I was afraid that a change to syscall might have changed some behavior so that was what I checked in those 10 minutes earlier today. The pointer that is returned here is a pointer to the first 16 bit UTF-16 character of the string. In C a string is represented as a pointer to the memory where the string starts, i.e. a pointer to its first character. By convention the string length is from the start to the first 0 character. This function creates a UTF-16 character for each rune in `s` and appends a `0`.

**Comment by gonutz** [comment] 2021-07-28 20:09
I suspect that I introduced a bug in either the `w32` library, which wraps the Windows API, or in the `wui` code itself. I rarely use the `StringTable` in real life so it is not well-tested at all.

**Comment by ReinforceZwei** [comment] 2022-01-18 07:37
Hi, 

I'm facing the exact same problem. Is there any chance to get this bug fixed?

**Comment by gonutz** [comment] 2022-01-18 07:44
Hey there! Unfortunately I have no free time to work on this right now. This library takes a lot of time to move forward, having a good API while wrestling with the details of the Windows API and testing all of it is very time consuming. I hope that some day I can return to this and get some major updates in but for now I depend on contributions, which there are almost none of. This repo does not have wide visibility at the moment. So I am sorry, there is a chance to get this fixed, but it is not going to be any time soon.

Except if you want to hop in and bite your teeth on the Windows API :-D

**Comment by ReinforceZwei** [comment] 2022-01-19 08:42
Hi,

After playing around, I'm able to fix the problem by simply passing the header string in ASCII encoding. As a result, full letters can be displayed properly.
![image](https://user-images.githubusercontent.com/39955851/150093756-61303283-3c4e-45b4-8a4b-bb7f8fdcccdd.png)

However, as I'm passing ASCII encoded string, non-ascii characters cannot be displayed properly.

See my change below: (also, type of `PszText` was changed from `*uint16` to `uintptr`)
![image](https://user-images.githubusercontent.com/39955851/150094243-63c36a17-812d-4937-baca-6316216a0ab1.png)

Since I'm not an expert of writing Go, I'll just left my message here instead of opening PR.

**Comment by ReinforceZwei** [comment] 2022-01-19 12:08
Hi,

After reading a lot of MS Docs, I finally fixed the problem. The problem is in `w32` package, the message ID for `LVM_INSERTCOLUMN` is Ansi version. The ID for Unicode version is `4193`, as stated [here](https://wiki.winehq.org/List_Of_Windows_Messages) (`LVM_INSERTCOLUMNW`). After changing the ID, the table header works great.
![image](https://user-images.githubusercontent.com/39955851/150125533-d4b84656-14d4-488b-85b5-4d09ac5fe637.png)

Hope this could help you fixing the issue.

**Comment by gonutz** [comment] 2022-01-19 18:54
Hey, nice job! Once I am back (in the next days) at my Windows machine, I will take a look at these and update the `w32` library and the dependency on it in `wui`. Thank you very much for spending your effort on this project, I really appreciate it! :-)

**Closed** 2022-01-23 09:04 UTC

**Comment by gonutz** [comment] 2022-01-23 09:58
I updated all the LVM_ constants and made a new tag for your go module to reference. :-)
